name: Deploy to Ubuntu Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            echo "Starting deployment..."

            # پاک کردن کامل دایرکتوری قبلی
            cd /var/www/
            rm -rf downSite
            mkdir -p downSite
            cd downSite

            echo "Cloning fresh repository..."
            git clone --depth 1 https://github.com/mhmdalisadat/exersize_builder.git . || { echo "Git clone failed"; exit 1; }

            echo "Installing dependencies..."
            rm -rf node_modules package-lock.json
            npm install || { echo "npm install failed"; exit 1; }

            echo "Installing Rollup..."
            npm install rollup || { echo "Rollup install failed"; exit 1; }

            echo "Building project..."
            npm run build || { echo "Build failed"; exit 1; }

            if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
              echo "Error: dist folder or index.html not found"
              exit 1
            fi

            echo "Checking dist directory contents:"
            ls -la dist/

            echo "Restarting PM2 service..."
            pm2 delete downSite || echo "No existing PM2 process found"
            NODE_NO_WARNINGS=1 pm2 start http-server --name downSite -- /var/www/downSite/dist -p 7074 --cors || { echo "PM2 start failed"; exit 1; }
            pm2 save || { echo "PM2 save failed"; exit 1; }

            echo "Deployment completed successfully"